#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  nasOS Display Setup
#  Reads /opt/nasos/data/display.json and applies:
#   1. Firmware hint via config.txt  display_rotate=N
#   2. Console text rotation via cmdline.txt  fbcon=rotate:N
#   3. Touch calibration via udev libinput rule
#   4. Display overlays (dtoverlay=…) in config.txt
#
#  Uses the primary display's rotation for firmware/console hints.
#  Per-output Wayland rotation is handled by cage-session.sh via
#  wlr-randr, NOT by kernel parameters.
#
#  Overlay management uses a marked block in config.txt so only
#  nasOS-managed overlays are touched — user-added lines outside
#  the block are left intact.
#
#  Run by:
#   • Backend display API after saving new settings (sudo)
#   • nasos-electron.service ExecStartPre (touch rule refresh)
#
#  A reboot is required for cmdline.txt/config.txt changes.
# ═══════════════════════════════════════════════════════════════
set -uo pipefail

CONFIG="/opt/nasos/data/display.json"
UDEV_RULE="/etc/udev/rules.d/99-nasos-touch-cal.rules"
OVERLAY_BLOCK_START="# nasOS display overlays — start"
OVERLAY_BLOCK_END="# nasOS display overlays — end"

# ── Locate boot partition files ──────────────────────────────────
BOOT_DIR=""
if [ -d /boot/firmware ]; then
  BOOT_DIR="/boot/firmware"
elif [ -d /boot ]; then
  BOOT_DIR="/boot"
fi

CONFIG_TXT="${BOOT_DIR:+$BOOT_DIR/config.txt}"
CMDLINE_TXT="${BOOT_DIR:+$BOOT_DIR/cmdline.txt}"

# ── Read display.json (multi-display aware) ──────────────────────
ROTATION=0
TOUCH_ROTATION=""
PRIMARY_CONNECTOR=""
OVERLAYS_JSON="[]"

if [[ -f "$CONFIG" ]]; then
  PRIMARY_CONNECTOR=$(python3 -c "
import json, sys
d = json.load(open(sys.argv[1]))
print(d.get('primary_connector', d.get('connector', '')))
" "$CONFIG" 2>/dev/null || echo "")

  ROTATION=$(python3 -c "
import json, sys
d = json.load(open(sys.argv[1]))
pc = d.get('primary_connector', d.get('connector', ''))
dc = d.get('display_configs', {})
cfg = dc.get(pc, {}) if pc else {}
print(cfg.get('rotation', d.get('rotation', 0)))
" "$CONFIG" 2>/dev/null || echo 0)

  TOUCH_ROTATION=$(python3 -c "
import json, sys
d = json.load(open(sys.argv[1]))
pc = d.get('primary_connector', d.get('connector', ''))
dc = d.get('display_configs', {})
cfg = dc.get(pc, {}) if pc else {}
tr = cfg.get('touch_rotation', d.get('touch_rotation'))
print('' if tr is None else tr)
" "$CONFIG" 2>/dev/null || echo "")

  OVERLAYS_JSON=$(python3 -c "
import json, sys
d = json.load(open(sys.argv[1]))
print(json.dumps(d.get('display_overlays', [])))
" "$CONFIG" 2>/dev/null || echo "[]")
fi

TOUCH_AUTO=true
if [[ -n "$TOUCH_ROTATION" ]]; then
  TOUCH_AUTO=false
fi

# ── Map degrees → firmware value (0=0° 1=90° 2=180° 3=270°) ─────
case "$ROTATION" in
  90)  FW_ROTATE=1 ;;
  180) FW_ROTATE=2 ;;
  270) FW_ROTATE=3 ;;
  *)   FW_ROTATE=0 ;;
esac

# ── 1. config.txt — display_rotate (firmware hint) ───────────────
if [[ -n "$CONFIG_TXT" && -f "$CONFIG_TXT" ]]; then
  sed -i '/^display_rotate=/d' "$CONFIG_TXT"
  echo "display_rotate=$FW_ROTATE" >> "$CONFIG_TXT"
  echo "  config.txt: display_rotate=$FW_ROTATE"
fi

# ── 2. cmdline.txt — fbcon=rotate (console text) ─────────────────
# Clean up any video=…rotate/panel_orientation entries left by
# previous versions of this script.  Wayland rotation is handled
# by wlr-randr in cage-session.sh, not kernel parameters.
if [[ -n "$CMDLINE_TXT" && -f "$CMDLINE_TXT" ]]; then
  CMDLINE=$(cat "$CMDLINE_TXT")

  # Strip legacy video=…rotate… / panel_orientation… and old fbcon=rotate
  CMDLINE=$(echo "$CMDLINE" | sed -E \
    -e 's/video=[^ ]*(rotate|panel_orientation)=[^ ]*//g' \
    -e 's/fbcon=rotate:[0-9]+//g' \
    -e 's/[[:space:]]+/ /g; s/^ //; s/ $//')

  CMDLINE="$CMDLINE fbcon=rotate:$FW_ROTATE"

  echo "$CMDLINE" | tr -s ' ' > "$CMDLINE_TXT"
  echo "  cmdline.txt: fbcon=rotate:$FW_ROTATE"
fi
# ── 3. Touch calibration (libinput matrix via udev) ─────────────
# The touch digitizer on this panel is physically rotated 90° from
# the display, so auto mode adds +90° to the screen rotation.
# Custom mode lets the user override with an explicit angle.
#   0°:   1  0 0  0  1 0  (identity)
#   90°:  0 -1 1  1  0 0
#  180°: -1  0 1  0 -1 1
#  270°:  0  1 0 -1  0 1
touch_matrix_for_angle() {
  case "$1" in
    90)  echo "0 -1 1 1 0 0" ;;
    180) echo "-1 0 1 0 -1 1" ;;
    270) echo "0 1 0 -1 0 1" ;;
    *)   echo "1 0 0 0 1 0" ;;
  esac
}

if $TOUCH_AUTO; then
  # Compensate for 90° physical offset between digitizer and panel
  TOUCH_ANGLE=$(( (ROTATION + 90) % 360 ))
  MATRIX=$(touch_matrix_for_angle "$TOUCH_ANGLE")
  TOUCH_LABEL="auto (screen ${ROTATION}° + 90° offset → touch ${TOUCH_ANGLE}°)"
else
  MATRIX=$(touch_matrix_for_angle "$TOUCH_ROTATION")
  TOUCH_LABEL="custom (${TOUCH_ROTATION}°)"
fi

cat > "$UDEV_RULE" <<EOF
# nasOS touch calibration — auto-generated by display-setup.sh
# Primary: ${PRIMARY_CONNECTOR}  Screen rotation: ${ROTATION}°  Touch: ${TOUCH_LABEL}
# Re-generated on every boot and when settings change via the web UI.
ACTION=="add|change", SUBSYSTEM=="input", ENV{ID_INPUT_TOUCHSCREEN}=="1", ENV{LIBINPUT_CALIBRATION_MATRIX}="$MATRIX"
EOF

udevadm trigger --subsystem-match=input 2>/dev/null || true

# ── 4. Display overlays in config.txt ─────────────────────────────
# Manage a marked block so we only touch nasOS-controlled lines.
if [[ -n "$CONFIG_TXT" && -f "$CONFIG_TXT" ]]; then
  # Build the new overlay block content
  OVERLAY_LINES=$(python3 -c "
import json, sys
overlays = json.loads(sys.argv[1])
for o in overlays:
    o = o.strip()
    if o:
        print(f'dtoverlay={o}')
" "$OVERLAYS_JSON" 2>/dev/null || echo "")

  # Remove existing nasOS overlay block (if any)
  if grep -qF "$OVERLAY_BLOCK_START" "$CONFIG_TXT" 2>/dev/null; then
    sed -i "/$OVERLAY_BLOCK_START/,/$OVERLAY_BLOCK_END/d" "$CONFIG_TXT"
  fi

  # Write new block (even if empty, keeps the markers for clean state)
  if [[ -n "$OVERLAY_LINES" ]]; then
    {
      echo ""
      echo "$OVERLAY_BLOCK_START"
      echo "$OVERLAY_LINES"
      echo "$OVERLAY_BLOCK_END"
    } >> "$CONFIG_TXT"
    echo "  config.txt overlays: $(echo "$OVERLAY_LINES" | wc -l | tr -d ' ') entries"
  else
    echo "  config.txt overlays: none"
  fi
fi

echo "nasOS display-setup: primary=${PRIMARY_CONNECTOR} screen=${ROTATION}° touch=${TOUCH_LABEL}"
